repos:
-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    -   id: isort

-   repo: https://github.com/psf/black
    rev:  23.12.1
    hooks:
    -   id: black
        language_version: python3.7

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=5120']
    -   id: trailing-whitespace
        files: (\.py|\.rst|\.yaml|)$
    -   id: check-merge-conflict

-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        # To turn this into an error, remove --exit-zero below
        args: ['--config', '.flake8.config','--exit-zero']
        verbose: true

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.8.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        additional_dependencies: [tokenize-rt==3.2.0]
ci:
  autoupdate_schedule: 'quarterly'
