repos:
    # Isort official mirror - we should update to this when it is black compatible.
    #-   repo: https://github.com/pre-commit/mirrors-isort
    #    rev: v4.3.17_black
    # For now use a custom fork isort that is patched to be black compatible
-   repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
    -   id: isort

-   repo: https://github.com/ambv/black
    # 19.3b0 has a bug with from future use print in python2.7
    # Use a commit afterwards that fixes it
    rev:  20.8b1
    hooks:
    -   id: black
        language_version: python3.8

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=5120']
    -   id: trailing-whitespace
        files: (\.py|\.c|\.cpp|\.h|\.cu|\.rst|\.yaml|\.sh|\.launch|Jenkinsfile|.clang-format)$
    -   id: check-merge-conflict

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
    -   id: flake8
        # To turn this into an error, remove --exit-zero below
        args: ['--config', '.flake8.config','--exit-zero']
        verbose: true